//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hello.ConcatenatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.mycompany.com/", ConfigurationName="ConcatenatorService.Concatenator")]
    public interface Concatenator {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Hello.ConcatenatorService.concatenateResponse concatenate(Hello.ConcatenatorService.concatenateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class concatenateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="concatenate", Namespace="http://webservice.mycompany.com/", Order=0)]
        public Hello.ConcatenatorService.concatenateRequestBody Body;
        
        public concatenateRequest() {
        }
        
        public concatenateRequest(Hello.ConcatenatorService.concatenateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class concatenateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public concatenateRequestBody() {
        }
        
        public concatenateRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class concatenateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="concatenateResponse", Namespace="http://webservice.mycompany.com/", Order=0)]
        public Hello.ConcatenatorService.concatenateResponseBody Body;
        
        public concatenateResponse() {
        }
        
        public concatenateResponse(Hello.ConcatenatorService.concatenateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class concatenateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public concatenateResponseBody() {
        }
        
        public concatenateResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ConcatenatorChannel : Hello.ConcatenatorService.Concatenator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConcatenatorClient : System.ServiceModel.ClientBase<Hello.ConcatenatorService.Concatenator>, Hello.ConcatenatorService.Concatenator {
        
        public ConcatenatorClient() {
        }
        
        public ConcatenatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConcatenatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcatenatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConcatenatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hello.ConcatenatorService.concatenateResponse Hello.ConcatenatorService.Concatenator.concatenate(Hello.ConcatenatorService.concatenateRequest request) {
            return base.Channel.concatenate(request);
        }
        
        public string concatenate(string arg0, string arg1) {
            Hello.ConcatenatorService.concatenateRequest inValue = new Hello.ConcatenatorService.concatenateRequest();
            inValue.Body = new Hello.ConcatenatorService.concatenateRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            Hello.ConcatenatorService.concatenateResponse retVal = ((Hello.ConcatenatorService.Concatenator)(this)).concatenate(inValue);
            return retVal.Body.@return;
        }
    }
}
